config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :users do
    resources :posts, only: %i[create update destroy]
  end

  resources :posts do
    get :search, on: :collection
    resources :answers do
      member do
        post 'vote'
        post 'devote'
        post 'answer'
      end
    end
  end

  post 'answer/:id/answers', to: 'answers#create_answer', as: 'answer_answers'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_many :answers, :as => :answerable
  belongs_to :answerable, :polymorphic => true
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { includes(:answers).order('answers.votes desc') }

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings do
    mappings dynamic: false do
      indexes :title, type: :text, analyzer: :english
      indexes :description, type: :text, analyzer: :english
    end
  end

  def self.search(query)
    __elasticsearch__.search({
      query: {
        multi_match: {
          query: query,
          fuzziness: 'AUTO',
          fields: %w[title body]
        }
      }
    })
  end

  belongs_to :user
  has_many :answers, :as => :answerable

  after_commit :flush_cache

  def total_votes
    answers.sum(:votes)
  end

  def flush_cache
    Rails.cache.delete(['user', id])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_secure_password
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :find_post

  def create
    create_answer(@post)

    redirect_to post_path(@post)
  end

  def answer
    @answer = Answer.find(params[:id])
    create_answer(@answer)

    redirect_to post_path(@post)
  end

  def vote
    @answer = Answer.find(params[:id])
    current_votes = @answer.votes
    @answer.update(votes: current_votes + 1)

    redirect_to post_path(@post)
  end

  def devote
    @answer = Answer.find(params[:id])
    current_votes = @answer.votes
    @answer.update(votes: current_votes - 1)

    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def answer_params
    params.require(:answer).permit(:description)
  end

  def create_answer(parent)
    Answer.create(answer_params.merge(user_id: current_user.id, answerable: parent))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :logged_in_user, except: [:show, :index, :search]

  def index
    @posts = Rails.cache.fetch('posts', expires_in: 1.minutes) { Post.all }
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def search
    @posts = Post.search(params[:search]).records.to_a
    render 'index'
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user&.authenticate(params[:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if user_params[:password] == user_params[:password_confirmation] && @user.save
      log_in @user
      flash[:success] = 'Welcome to the app!'
      redirect_to root_path
    else
      @user.errors.add(:base, 'Both the passwords should be same.') if user_params[:password] != user_params[:password_confirmation]
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href='<%= root_path %>'>
        <%= image_tag "logo.jpeg", alt: "Avatar Logo", style: "width:40px;", class: "rounded-pill" %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href='<%= root_path %>'><h2>Quora</h2></a>
          </li>
        </ul>
      </div>
      <% if logged_in? %>
        <ul class="nav navbar-right ">
  	      <li><%= link_to 'Post Question', new_post_path %></li>
          <li><%= link_to "Log out", logout_path, class: "mx-2", method: :delete %></li> 
        </ul>
      <% else %>
        <ul class="nav navbar-right ">
          <li><%= link_to "Log in", login_path, class: "mx-2" %></li> 
          <li><%= link_to "Sign up", signup_path, class: "mx-2" %></li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class='container'>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/index.html.erb
<div class="container d-flex justify-content-center">
	<div class="card mt-5 p-4">
		<div class="mb-3">
			<%= form_tag search_posts_path, :method => :get do %>
				<%= text_field_tag :search, "", class: 'form-control', placeholder: "Search" %>
				<%= submit_tag "Search", { class: "mt-2 btn btn-primary" } %>
			<% end %>
		</div>
		<span class="text mb-4">Question Feeds</span>
		<% @posts.each do |post| %>
			<%= link_to post_url(post), class: 'post-link' do %>
				<div class="d-flex flex-row justify-content-between mb-3">
					<div class="d-flex flex-column p-3">
						<p class="mb-1"><%= post.title %></p> 
						<small class="text-muted"><%= post.description %></small>
					</div>
					<div class="price pt-3" style="padding-left: 10px;">
						<span class="mb-2">Total Votes</span>
						<h5><%= post.total_votes %></h5>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container d-flex justify-content-center">
	<div class="card mt-5 p-4">
    <strong class='post-title'>Post a Question</strong><br />
    <% if @post.errors.any? %>
      <strong style='font-size: 20px;'>Errors</strong><br />
      <div id="error_explanation">
        <h2>
          <%= pluralize(@post.errors.count, "error") %> prohibited
          this post from being saved:
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for :post, url: user_posts_path(1) do |f| %>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </p>
      <p>
        <%= f.submit %>
      </p>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="container d-flex justify-content-center">
	<div class="card mt-5 p-4">
    <strong class='post-title'>Q. <%= @post.title %></strong><br />
    <small class='post-description'><%= @post.description %></small>
    <hr />
    <strong style='font-size: 20px;'>Answers</strong><br />
    <%= "<div style='color: grey; text-align: center;'>No Answers</div>".html_safe if @post.answers.length == 0 %>
    <% @post.answers.each do |answer| %>
      <div style="margin-bottom: 15px;">
        <div class="votes-container">
          <div class="icons"> 
            <%= link_to "<div class='vote-icon-container'>^</div>".html_safe, vote_post_answer_path(@post, answer.id), method: "post", class: "voting-icon"  %> 
            <%= link_to "<div class='vote-icon-container' style='transform: rotate(180deg); display: inline-block;'>^</div>".html_safe, devote_post_answer_path(@post, answer.id), method: "post", class: "voting-icon" %>
          </div>
          <div class="count"><%= answer.votes %></div>
          <div class="answer-details">
            <div>
              <span style="font-weight: bold;"><%= answer&.user&.name %></span>
              <span style="font-size: 12px;">Updated on: <i><%= answer&.updated_at.localtime.strftime("%F Time: %T") %></i><span>
            </div>
            <div style="font-size: 15px; font-family: monospace;">
              <%= answer.description %>
            </div>
            <div class="replies">
              <ul>
                <% answer.answers&.each do |reply| %>
                  <li><%= "#{reply&.description} - <i>#{reply.user.name}</i>".html_safe %>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div style="padding-left: 60px;">
          <%= form_tag answer_post_answer_path(@post, answer), :method => :post do %>
            <%= label_tag 'Reply to answer' %>
            <%= text_area_tag 'answer[description]', "", class: 'form-control', placeholder: "Reply...." %>
            <%= submit_tag "Reply", { class: "mt-2 btn btn-primary", disabled: !logged_in? } %>
          <% end %>
        </div>
      </div>
    <% end %>
    <hr />
    <strong style='font-size: 20px;'>Post your answer</strong><br />
    <%= form_for([@post, @post.answers.build]) do |f| %>
      <p>
        <%= f.label :Answer %><br>
        <%= f.text_area :description, class: 'form-control', placeholder: "Answer...." %>
      </p>
      <p>
        <%= f.submit "Submit Answer", disabled: !logged_in?, class: "mt-2 btn btn-primary" %>
      </p>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class='text-danger'><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container d-flex justify-content-center">
	<div class="card mt-5 p-4">
		<div class="input-group mb-3">
      <form class="d-flex">
        <input class="form-control me-2" type="text" placeholder="Search">
        <button class="btn btn-primary" type="button"><i class="fas fa-search"></i>Search</button>
      </form>
		</div>
		<span class="text mb-4">88 branding projects</span>
		<div class="d-flex flex-row justify-content-between mb-3">
			<div class="d-flex flex-column p-3"><p class="mb-1">Logo and marketing material design for Bakery</p> <small class="text-muted">8 days remaining</small>
			</div>
			<div class="price pt-3 pl-3">
				<span class="mb-2">Fixed</span>
				<h5><span>&dollar;</span>1,500</h5>
			</div>
		</div>
		<div class="d-flex flex-row justify-content-between mx-1">
			<div class="d-flex flex-column p-3"><p class="mb-1">Need to create brand guidelines for my brand</p> <small class="text-muted">12 days remaining</small>
			</div>
			<div class="price pt-3 pl-3">
				<span class="mb-2">Hourly</span>
				<h5><span>&dollar;</span>40</h5>
			</div>
		</div>
		<div>
			<h3>Question Feeds</h3>
				<% @posts.each do |post| %>
					<%= link_to post.title, post_url(post) %>
				<% end %>
		</div>
	</div>
	<% if logged_in? %>
  	<%= link_to 'Post Question', new_post_path %>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="row justify-content-md-center h-100">
    <div class="card-wrapper">
      <div class="card mt-5 p-4">
        <div class="card-body">
          <h4 class="card-title">Sign up</h4>
            <%= form_for @user, html: {class: "nifty_form"}, local: true do |f| %>
              <%= render 'shared/error_messages' %>
              <div class="form-group">
                <label for="email">E-Mail Address</label>
                <%= f.text_field :email, class: 'mb-1 form-control' %>
              </div>
              <div class="form-group">
                <label for="password">First Name</label>
                <%= f.text_field :first_name, class: 'mb-1 form-control' %>
              </div>
              <div class="form-group">
                <label for="password">Last Name</label>
                <%= f.text_field :last_name, class: 'mb-1 form-control' %>
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <%= f.password_field :password, class: 'mb-1 form-control' %>
              </div>
              <div class="form-group">
                <label for="password">Password Confirmation</label>
                <%= f.password_field :password_confirmation, class: 'mb-1 form-control' %>
              </div>

              <div class="form-group m-0">
                <%= f.submit "Create my account", class: "btn btn-primary btn-block mt-3" %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>